### ISSUE TITLE
Files referenced in CSV inputs should allow absolute or relative paths

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1025]
I believe a number of models are setup this way already, (CV, REC, HRA?), but Habitat Quality only supports relative paths right now, as discussed https://community.naturalcapitalproject.org/t/csv-a-threat-raster-for-threats-manre-cur-path-waterre-cur-path-luodire-cur-path-shuitianre-cur-path-was-not-found-or-it-could-not-be-opened-by-gdal/2887/8

I'm not sure if there are some helpful utilities in `utils` to facilitate this, but there could be if it makes sense.

**Comment by emlys** [comment]
Confirmed there are 5 models that use CSVs with paths: CBC, CV, HQ, HRA, and recreation. Definitely enough cases to justify a utils function.

**Comment by emlys** [comment]
As part of this work, we decided to remove the logic in HRA that handles cross-platform paths (expanding a relative path from windows when running on mac: `'Users/emily/Documents' + 'foo\bar.tif'`)

invest does not handle cross-platform paths, and users need to make sure that any path separators in paths in CSVs are correct for their platform. Because windows recognizes both `\` and `/` as path separators, it's easiest to just use `/` everywhere.
