### ISSUE TITLE
SDR outputs should be consistent with how nodata is handled within streams

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1068]
This came up from @newtpatrol in a round of feedback on the 3.12 release.

2 examples from SDR with the 3.12 version:

* Model-defined streams in `sed_deposition.tif` have nodata in the streams
* `sed_export.tif` has data defined within the streams, though it appears to have values of 0 in the streams

We should figure out what the right standard here should be and then be consistent with this throughout the model outputs.

**Comment by newtpatrol** [comment]
It also just came to my attention that the export outputs in NDR have NoData in streams, so this is also inconsistent between models.

**Comment by emlys** [comment]
I think this has changed a bit since the issue was originally reported. Of the SDR outputs that derive from the stream/drainage raster, most have nodata in streams (IC, SDR, E', sediment export, sediment deposition, avoided export). Those that have valid data in streams are:
- RKLS: set to 1 in streams. This is questionable, I will ask Rafa
- USLE: set to 0 in streams. This might make sense, I will ask Rafa
- D_dn: 0 in streams. This makes sense intuitively - the distance downslope to a stream from a stream is 0.
- avoided erosion: 1 in streams (RKLS - USLE). This is questionable and will depend on the decision for RKLS and USLE.

**Comment by emlys** [comment]
Similarly for NDR outputs that derive from streams:
- distance to channel: 0 in streams. This makes sense intuitively
- D_dn: 0 in streams. This makes sense intuitively
- IC: nodata in streams. This makes sense intutitively (IC = D_up/D_dn, undefined where D_dn = 0)
- eff (max retention efficiency for LULC): 0 in streams. I think this makes sense (?)
- critical length: 0 in streams. ??
- effective retention: 0 in streams. ??
- NDR: nodata in streams
- surface export: nodata in streams
- subsurface NDR: 1 in streams. ??
- subsurface export: 0 in streams. ??
- total export: nodata in streams

**Comment by emlys** [comment]
@newtpatrol after looking at this more, I'm not sure I agree that all the outputs should be consistent about having nodata in streams. Some outputs can't be calculated in streams, while other outputs can be. Some intermediate outputs _have_ to have data in streams, or else it causes large data gaps in the results.

There was one actual bug, where RKLS was set to 1 on streams, and we fixed that here: https://github.com/natcap/invest/issues/1415
But I couldn't identify any other issues. Is there a particular case where you need nodata to line up and/or the results aren't intuitive?

**Comment by newtpatrol** [comment]
Hm. Well, if there are science/coding reasons for there to be stream results in some outputs but not others, then I guess they should stay that way. It does seem inconsistent at least between NDR and SDR if some of the main export/retention results (not intermediates, I'm not generally concerned about those) are NoData and others aren't, especially since we say that we don't do in-stream processing, then sometimes do return results in streams.  (And when we don't return results in streams, it's sometimes annoying since the streams often cover large swaths of the AOI... sigh...)

In the grand scheme of things, I don't feel strongly enough about this to say it's any sort of priority.  It would be nice to at least have an easy-to-understand response for forum questions about why some have stream data and others don't. I also wonder if we should add a sentence to the relevant entries in the User Guide Interpreting Results section, specifically addressing what the values in streams means.

And I really appreciate your looking into it @emlys!

**Comment by emlys** [comment]
@newtpatrol I agree that we should have a better way to explain why there is or isn't data in a particular area. I made a separate ticket about incorporating this into the model spec: https://github.com/natcap/invest/issues/1450

As far as consistency in the NDR and SDR final outputs, it looks like all of them have nodata in streams except for nitrogen subsurface export and sediment deposition. Let me know if that seems incorrect, otherwise I think we can close this issue.

**Comment by newtpatrol** [comment]
If it were just sediment deposition, I'd feel ok about it. But if I run the sample data through SDR, sed_export.tif, sed_deposition.tif, avoided_erosion.tif and avoided_export.tif all have data in streams. sed_export.tif and avoided_export.tif mostly have values of 0, but often values > 0 within the streams defined by streams.tif.  avoided_erosion.tif looks more consistent within streams, with a value of 1.

**Comment by emlys** [comment]
@newtpatrol, I just ran SDR (3.14.1) on the sample data and I'm seeing nodata in streams in sed_export.tif, avoided_erosion.tif, and avoided_export.tif. (Though I didn't run any raster calculator math to make sure, I just clicked around a bit.) Could you confirm if you're still experiencing this issue?

**Comment by newtpatrol** [comment]
The results do look consistent now with 3.14.1, thanks @emlys. Deposition still has values within streams, but that seems ok to me since that's where much of the export ends up.

**Comment by emlys** [comment]
Thanks @newtpatrol, I'm going to close this now and we can continue general discussion about documenting where nodata should exist in #1450
