### ISSUE TITLE
LULC and Biophysical table should mention LULC codes are unique

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1077]
@newtpatrol mentioned in a Slack thread that:

>... the User Guide description for LULC and biophysical table do not specify that the integer codes must be unique. Since this seems like a quality that is common across all models that use an LULC and biophysical table, and these are now defined in the UG with investspec, I'd like to request that this be added to their description. This might involve changes to different inputs in different models (like current, future and baseline land cover in Habiat Quality), so will take a bit of thoroughness to check each model.

For LULC that should be an easy add in `spec_utils` where we define a LULC about section.

**Comment by davemfish** [comment]
Maybe I'm not interpreting this correctly, but values in an LULC raster should not all be unique (that would be very rare, anyway). LULC codes in a `lucode` column of a biophysical table do need to be unique.

**Comment by newtpatrol** [comment]
Right Dave, sorry for the imprecision. The LULC raster's Values must be unique, as well as the biophysical table's corresponding lucode values. I wasn't talking about the parameter values (usle_c, kc, CN etc) also in the biophysical table.

~ Stacie

________________________________

**Comment by newtpatrol** [comment]
Yes, it's all about having unique lucodes. I said "LULC raster's Values" because "value" is the column that shows in ArcGIS with those unique codes. Of course, QGIS still stubbornly refuses to let us look at raster attribute tables, so I guess it would be confusing to call them by something people who use Q can't see.

Oh, regarding accepting floats for lucodes, the "lucode" entry under Biophysical Table data requirements only specifies integer, and I've never seen anything in the UG about accepting values as floats with the specific format of xx.0. Should this info be added somewhere? (Personally, I'd be inclined to just require integer, seems easier).

How about something like this:

Current LULC entry in the UG: "Map of land use/land cover codes. All values in this raster must have corresponding entries in the Biophysical Table."

Suggestion for re-wording: "Map of land use/land cover codes. Each land use/land cover type must be assigned a unique integer code, which is used to map parameters from the Biophysical Table. All values (codes) in this raster must have corresponding entries in the Biophysical Table "lucode" column."

Current Biophysical Table lucode entry in the UG: "LULC code from the LULC raster."

Suggestion for re-wording: "LULC codes from the LULC raster. Each code must be a unique integer."

~ Stacie
________________________________

**Comment by newtpatrol** [comment]
Regarding Dave's musing about the sample table, I swear that at one point in the past I added verbiage to that table caption emphasizing that this was an example only and your classes and codes will probably be different. I feel like quite a few of my past updates to the UG got lost along the way, some of which probably don't matter, but some kinda do.

Since we don't provide an example for most of the other inputs, I don't feel strongly that we should keep this one, if it is indeed confusing. If we do keep it, perhaps we could give two different examples, as well as emphasize in text that your classes and codes will probably be different.

~ Stacie

________________________________
