### ISSUE TITLE
Puppeteer tests are flaky

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1186]
Lately it seems like the "Build binaries" workflow is most likely to randomly fail, and it usually fails on the puppeteer step. For example, on the latest commit on main, the checks [originally passed](https://github.com/natcap/invest/actions/runs/4127028065/attempts/1), but the mac binary build [failed on a rerun](https://github.com/natcap/invest/actions/runs/4127028065/attempts/2), with these errors:

> `objc[58407]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb54cadec8) and /Users/runner/work/invest/invest/workbench/dist/mac/InVEST 3.12.1.post21+gba5d36231 Workbench.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10b7e89c8). One of the two will be used. Which one is undefined.`

> `'Failed to fetch browser webSocket URL from http://localhost:9009/json/version: request to http://localhost:9009/json/version failed, reason: connect ECONNREFUSED ::1:9009'`

> `TypeError: Cannot read properties of undefined (reading 'close')
        at _callee2$ (/Users/runner/work/invest/invest/workbench/tests/binary_tests/puppet.test.js:133:19)
    expect(received).toBeTruthy()
        at tryCatch (/Users/runner/work/invest/invest/workbench/node_modules/regenerator-runtime/runtime.js:63:40)
    ...`

**Comment by davemfish** [comment]
Thanks for making this issue, this has been on my mind as well but I haven't come up with a solution. 

I think this traceback indicates that puppeteer never successfully connected to the electron child process, and the test eventually timed out and erred on the cleanup `afterAll` step.

There's one circumstance where I can actually explain why that would happen, but unfortunately I don't think it is the usual pattern:

An uncaught exception in the main electron process will raise an operating-system alert dialog with the traceback. Something like `"A Javascript error occurred in the main process..."`. If that happens, the alert blocks the `stderr` event handler on the electron subprocess, and so the subprocess remains open until the alert is closed, which is not something that seems possible in the VM context. 

We listen for `process.on('uncaughtException')` in `main.js`, so we should never get to that point, _except_ an exception raised from the `require` stack won't get caught, probably because the listener hasn't been registered yet. So, in the rare case where we have a missing dependency or something, this can play out. But I think that's rare so there is probably also some other reason why the electron subprocess sometimes does not startup smoothly before the test times out.

As an aside, I think we should improve the `stderr` listener in the test:
```javascript
ELECTRON_PROCESS.stderr.on('data', (data) => {
    console.log(`${data}`);
    process.exit(1)  // add this to exit the test much faster
});
```

And if we want to catch missing dependencies, like something listed under `devDependencies` that needs to be included in production, we could consider using `vite` to bundle the `main` process code, and I'm pretty sure it will complain at build time if we make this mistake.

**Comment by davemfish** [comment]
One other case I noticed: Occasionally the test fails on this query:

```
const cancelButton = await findByRole(sidebar,
    'button', { name: 'Cancel Run' }, { timeout: 5000 });
```
I believe it is simply timing out. Sometimes 5 seconds is not enough time for the all the events that happen between clicking "Run" and the "Cancel" button appearing. Since we're careful to not display a Cancel button until after we're certain the invest subprocess has started and the model is executing.
