### ISSUE TITLE
Error in "build binaries" job on macOS

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1508]
"Build binaries" job is failing with this error when it tries to run `invest list` on the built binaries.
```
subprocess.CalledProcessError: Command '['/Users/runner/work/invest/invest/dist/invest/invest', '-sS', '-c', 'import platform; print(platform.mac_ver()[0])']' returned non-zero exit status 2.
```

**Comment by davemfish** [comment]
This has happened in the past and we just waited it out. #1339. But that's not ideal.

The tracebacks are slightly different, in that now it's `scipy` using `packaging.tags` and before it was `numpy`. I'm not sure if that matters though.

**Comment by davemfish** [comment]
Looking a bit deeper, it seems like the same code existed in numpy and scipy to trigger this error from `packaging.tags`. `numpy` has since commented it out:
https://github.com/numpy/numpy/commit/5e84001b3d4b0af5cbbeec98af26476c27504439

But it remains in scipy:
https://github.com/scipy/scipy/commit/96081aa10e929e807b199f8e441dd1693e304f03#diff-d391aad2c82e14fc007b51754595db11588d209a2d3f6d15e6fb2538eea7b716

I tried making a minimal reproduction to report to scipy, but it doesn't raise an exception
https://github.com/davemfish/scipy-macos-repro/actions/runs/7888783411/job/21527071997

Maybe it only reproduces with pyinstaller binaries?

**Comment by davemfish** [comment]
I was able to make a minimal reproduction, so now there's a scipy issue: https://github.com/scipy/scipy/issues/20084
