### ISSUE TITLE
Catch missing uniform search radius in UI

### ISSUE THREAD

**Issue by newtpatrol** [natcap/invest#1509]
This issue was just [posted to the user forum](https://community.naturalcapitalproject.org/t/urban-nature-access-valueerror-encountered-nan-in-calculation-but-default-nan-is-none/4379/8), and I replicated it with Workbench 3.14.1. 

In Workbench, with Urban Nature Access, If the user chooses a "Search Radius Mode" of "Uniform radius", the model requires that the user also provide "Uniform Search Radius" in the user interface. But the Workbench UI does not show an error when a value for "Uniform Search Radius" is not provided when it is required (and instead, throws a not useful error at runtime). Based on the behavior of other models, I think this should be caught in the UI, or at the very least caught while running with a user-friendly error message.

Currently, this error gets thrown while running the model:

> 2024-01-22 19:32:39,229 (natcap.invest.utils) utils.prepare_workspace(166) ERROR Exception while executing natcap.invest.urban_nature_access
> Traceback (most recent call last):
>   File "natcap\invest\utils.py", line 164, in prepare_workspace
>   File "invest\cli.py", line 470, in main
>   File "natcap\invest\urban_nature_access.py", line 934, in execute
> ValueError: could not convert string to float: ''

**Comment by phargogh** [comment]
Looking into this, this looks like an issue with how I wrote the conditional requirement in the MODEL_SPEC.  The way conditional requirement is supposed to be written has to do with the presence and validity of another input.  The way I wrote it has to do with a specific _value_ of an option (like which search radius option was selected).  So this is a bug in the model spec and in the model's validation rather than the workbench.
