### ISSUE TITLE
Workbench: Saving datastack with absoluate paths uses relative paths anyway

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1609]
I tested using the Workbench and _not_ checking the "relative paths" option, and I got a datastack with relative paths.

**Comment by emilyanndavis** [comment]
Hi @davemfish, I found the root cause here. The `relativePaths` attribute on the SaveAsModal's state changes only on user interaction with the checkbox, so if you check it once, then close the modal (after completing the save, or otherwise), then open the modal again, `relativePaths` is still `true`, even though the checkbox is unchecked when the modal re-opens.

We have a couple of options—both very small and simple changes—wondering if you have an opinion?

1. Explicitly set `relativePaths` to `false` whenever the modal is opened. This keeps state in sync with the appearance of the checkbox, which is always unchecked when the modal opens.

2. Alternatively: set the `checked` attribute on the checkbox so that it remains in sync with the value of `relativePaths`. This would mean a minor change in the UX, namely: if you check the checkbox, then close the modal, then open the modal again, the checkbox will still be checked. This could come in handy if you're running a model several times with various inputs, and each time you want to save the datastack with relative paths, since you'd be saved the trouble of checking that checkbox each time. The caveat, of course, is that the checkbox is only "sticky" in the context of that particular tab.

**Comment by davemfish** [comment]
@emilyanndavis cool, thanks for looking into this. On one hand I prefer option 2 from the UX perspective, where the modal remembers the user's most recent choice. On the other hand, since that memory doesn't persist across tabs without a fair bit more engineering (we do have some persistent settings stored on disk), maybe it's just simpler and a more consistent experience to go with option 1. I'm happy with either, but if I was doing it I think I would choose 1.
