### ISSUE TITLE
Do we still need to .hgignore?

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#258]
Are we done with mercurial and this tracked ignore file?

**Comment by phargogh** [comment]
Nope!  This can be removed.

We decided not to replace this with a `.gitignore`, and this can be done individually anyways.  Could we provide an example `.gitignore` in the InVEST wiki?

**Comment by dcdenu4** [comment]
Adding a wiki page here: https://github.com/natcap/invest/wiki/Example-gitignore-file

**Comment by dcdenu4** [comment]
Removed in #329

**Comment by badaminatasha** [comment]
Hi all! I just discovered this project through https://opensustain.tech/ and would love to contribute where I can. I am curious though, what motivated the decision to forego a .gitignore? I've been playing around in a local fork and indeed the extraneous files are piling up. A simple gitignore with things like pycache dirs seems like it might be handy.

**Comment by phargogh** [comment]
Welcome to the InVEST issue tracker @badaminatasha !  It's been a while since we decided this, but I think the reasoning at the time was something along the lines of that not having a gitignore would be more likely to reveal files that aren't tracked, and anyone could always add their own .gitignore without committing it to the repo.

Having said that, I agree with you that there are very likely a bunch of files that we could safely add to a .gitignore (including pycache files, but also local swap files, etc.), without preventing an individual developer from having their own tweaks.

@natcap/software-team any thoughts on this?  I'll reopen the issue

**Comment by dcdenu4** [comment]
> but I think the reasoning at the time was something along the lines of that not having a gitignore would be more likely to reveal files that aren't tracked, and anyone could always add their own .gitignore without committing it to the repo.

That's my recollection as well. I'm not opposed to having a basic repo wide gitignore for file that would commonly be generated for everyone across different OS.

@badaminatasha have you worked in other open-source projects and find this to be common practice?

**Comment by phargogh** [comment]
FWIW, I'd definitely say this is a common practice ... so common that GitHub's new repo wizard gives you a bunch of cookiecutter `.gitignore` files to choose from based on the language you're working in!

But I'd also be interested in hearing more @badaminatasha about the .gitignores that you have found helpful in other repos you've been working in latelyi

**Comment by badaminatasha** [comment]
Yup I would agree they're super common practice. So far I've really only built the project locally and run pytest, and I've noticed it's possible to commit the following files that should ideally be ignored:
- pycache dirs
- node_modules dirs
- yarn.lock
- build/ dir
- .venv (since I'm using a python venv)
There's a website called gitignore.io where you can enter tools/languages used by your project and it'll produce an exhaustive gitignore for it. [Here's](https://www.toptal.com/developers/gitignore/api/python,visualstudio,visualstudiocode,node) one I got by entering python, visualstudio, vscode, and node, though maybe it makes more sense to start with a much simpler one like:
```
### Node ###
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Dependency directories
node_modules/
jspm_packages/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# dotenv environment variable files
.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*

### Python ###
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Flask stuff:
instance/
.webassets-cache

# Environments
.venv
```
I am surprised none of these files have been accidentally committed, out of curiosity, do y'all typically do development from terminal or by another method?

**Comment by phargogh** [comment]
I'll have to let everyone else chime in when they get a chance, but personally I live in the terminal with vim as my editor, so I'm _usually_ careful to avoid committing more than I mean to.  That doesn't mean I haven't slipped up from time to time!

I see you refer to `.venv`, has that become conventional in the venv world?  Most of the time we're usually using conda environments because it's easier to manage the bigger C dependencies like GDAL.

**Comment by badaminatasha** [comment]
@phargogh I think conda is very conventional, I just started development with a venv since I'm more familiar with them than conda. I think conda needs a meta.yaml and a couple other things for local build but I don't see one in the repo. I noticed #2550 so I figure things will be clarified there

**Comment by davemfish** [comment]
I don't mind if we add a `.gitignore` file. Having lived without one for so long, my problem is not accidentally committing an unwanted file (I never do `git add .`), but I do occasionally forget to `add` a new file.

**Comment by emlys** [comment]
I agree that it's very common to track a `.gitignore`, and it's helpful for new developers joining the project. I don't mind adding one, but I do think it should be pretty tightly limited to files that are generated by standard development in our project. 

I think part of the reason for _not_ including one was that we all use different development tools that produce different files that need to be ignored. For instance, I don't use `venv` and it's not part of any natcap.invest tooling. So I don't think `.venv` belongs in a repo-level `.gitignore`. Things like that specific to your personal dev environment can go in a `.gitignore` in your home directory (I do this for `.DS_Store` files on mac).
