### ISSUE TITLE
Investigate sqlite console errors

### ISSUE THREAD

**Issue by emlys** [natcap/invest#338]
I came across these messages in the mac console app while debugging another issue:
<img width="1013" alt="Screen Shot 2020-10-12 at 3 58 33 PM" src="https://user-images.githubusercontent.com/43770515/95794208-9b068e00-0ca4-11eb-872d-03505e84d59f.png">

They show up immediately after clicking Run on SWY (probably other models too?). The model still appears to run okay but it's worth checking that this isn't a problem.

**Comment by emlys** [comment]
Possibly harmless and related to InVEST being unsigned

**Comment by phargogh** [comment]
Following up on this [from the conversation over on #322 ](https://github.com/natcap/invest/issues/322#issuecomment-709596696), [this StackExchange post](https://apple.stackexchange.com/questions/339509/edit-tcc-db-to-bypass-foo-app-wants-access-to-control-bar-app-on-own-machi) suggests that TCC's database is stored in an sqlite format, so that sounds like a plausible explanation for why this error is happening and why signing (even self-signing) might be enough to resolve the errors.

**Comment by emlys** [comment]
Tried this again and I'm only seeing `taskgated MacOS error: -67062`, none of the other `taskgated` messages. Assuming they were resolved by adding a code signature. Checking the error code with `security error -67062` I get
`Error: 0xFFFEFA0A -67062 code object is not signed at all` which is strange because we are signing the DMG. _(perhaps because we are signing the DMG, and not recursively signing the binaries, it doesn't know that they are signed, esp. when they are copied out of the DMG into Applications/?)_

We do know that the OS is recognizing the signature to some extent, because the app wouldn't launch when our certificate was accidentally revoked (revoked is more serious than not having signature at all).

So I'm going to close this. When we get Apple Developer access and an Apple certificate we can revisit this.

**Comment by phargogh** [comment]
> (perhaps because we are signing the DMG, and not recursively signing the binaries, it doesn't know that they are signed, esp. when they are copied out of the DMG into Applications/?)

This sounds likely to me!  Apple's Gatekeeper (I think ... it might be a different process) is careful to propagate the quarantine tag to any applications copied out of a DMG, but the digital signature is something that (I think) should be carried with the application so that the OS can verify that the application has remained unchanged on launch.
