### ISSUE TITLE
Look into documentation generating tools

### ISSUE THREAD

**Issue by emlys** [natcap/invest#339]
There are [several tools](https://wiki.python.org/moin/DocumentationTools) for generating API documentation from docstrings. We could make use of one of these to fill in the "Full API Reference" section of https://invest.readthedocs.io, since currently most of the models aren't described there.

We could also look into generating parts of the user's guide e.g. Data Needs and Interpreting Results sections from docstrings to maintain consistency with the model. This would avoid duplicating information and prevent simple but critical issues, like output values being per pixel vs. per hectare.

It would be really cool if we could somehow link the equations displayed in the user's guide to where they're implemented in the model code. Not sure if any existing tools allow you to extract information outside of docstrings though.

**Comment by phargogh** [comment]
Hey @emlys , thanks for pointing out these couple of issues with our API docs!  I just wanted to add a few other notes/things to think about while we're addressing this:

> currently most of the models aren't described there.

The invest.readthedocs.io build pulls information directly from public docstrings of `natcap.invest` any time we push to `main` or have a release.  If something isn't showing up, that's more likely an issue with RST formatting than anything else.  I've been thinking for some time that it could be helpful to programmatically check the format of our docstrings as part of our regular review cycle, so maybe this is the time?

For whoever takes this on, `make apidocs` will build the api docs locally and let me know if you'd like to be added to the readthedocs project!

> We could also look into generating parts of the user's guide e.g. Data Needs and Interpreting Results sections from docstrings to maintain consistency with the model. This would avoid duplicating information and prevent simple but critical issues, like output values being per pixel vs. per hectare.

There are undoubtedly parts of the user's guide that could stand to be de-duplicated, and now that we have an `ARGS_SPEC` structure, it could be easier to do that on demand for the model inputs.

But also, it's OK that there's a degree of duplication between the UG and our docstrings since they're intended for different audiences. Of course it's frustrating when we make a mistake or there's an inconsistency, but it's OK and it happens.  That doesn't mean that we shouldn't take reasonably precautions (of course we should!), and de-duplicating information in places where we can is probably a good idea.  But since these two resources are intended for different audiences, they'll necessarily be distinct resources.

And as an aside, if we make structural changes to the UG, we should be sure to design it and ask some regular contributors to the UG outside the SW Team to take a look (like Stacie).

**Comment by emlys** [comment]
Changing from 'enhancement' to 'bug' since we are using sphinx autodoc, it just hasn't been working correctly and some sections are very outdated.
