### ISSUE TITLE
Proposal: Include the python side of the workbench in this repo

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#341]
The Workbench is being developed in github.com/natcap/invest-workbench. It has some python dependencies including a small Flask app and `natcap.invest`. 

The workbench build process duplicates a lot of the invest build process, as it needs to package up frozen binaries for those python packages & dependencies. Those build processes (PyInstaller scripts & Actions workflows) are kind of high-maintenance in general - dealing with different OS, python & numpy versions, etc - so it's important to not duplicate them. 

### Proposal:
**Add a `release/workbench-alpha` branch to this repo and make the following changes:**
* Add the Workbench's `server.py` flask app
* Add tests for `server.py` - now they are in the workbench at `tests/flaskapp.test.js` but if they are to live in natcap/invest the tests should be refactored to python.
* Add a CLI endpoint like `invest serve` to launch the flask app
* ~~Add a section to the existing PyInstaller `invest.spec` to include `server.py` as a second entry-point~~
* Add `Flask` to `requirements-gui.txt` ~~(and remove the Qt reqs)~~
* rename `server.py` since it's not a server, it's a flask app that runs on a server
* Add or amend an Actions workflow to upload the PyInstaller output to a bucket where it can be retrieved by the Workbench's build process

The benefits are 1) less duplication and 2) much quicker workbench builds. 

The downside is that changes to the flask app during workbench development will have to be made in a different project from the rest of the workbench. Though it is possible to test local flask app changes in the workbench without running PyInstaller. Also, the flask app doesn't change too much. Even while the workbench is still very unstable in it's pre-alpha state, the `server.py` module rarely changes.

**Comment by phargogh** [comment]
This makes sense to me!  This would reduce our overall maintenance burden by keeping the InVEST builds in the same place and  by allowing for changes made in the active InVEST branches to be merged into `release/workbench-alpha`.  Sounds great, and especially since the HTTP interface has been pretty stable in practice.

In thinking about how we might include this in the invest repo, 
* If we're removing the Qt requirements, would this branch also remove the Qt UI and the GUI portion of the CLI?
* Would it be worth including this in the main InVEST CLI endpoint, akin to `hg serve` ... maybe `invest serve`?  The main advantages of doing so are that it would reduce build times (since only one binary would need to be generated), it would answer the question of where the binaries would be stored (we could use the existing bucket, though only some of the binaries pushed there would include the flask server), and it would keep all of the InVEST-related CLI entry points all in one place in a single binary.  That last point could be a downside too, if we wanted to hide the flask server from people who are running InVEST from the CLI.  There are probably other downsides there as well that I'm not thinking about.

**Comment by davemfish** [comment]
>     * If we're removing the Qt requirements, would this branch also remove the Qt UI and the GUI portion of the CLI?

Maybe this is premature. We've talked about distributing both UIs at first before completely ditching Qt. So removing the Qt UI stuff probably shouldn't happen right away.
 
>     * Would it be worth including this in the main InVEST CLI endpoint, akin to `hg serve` ... maybe `invest serve`?  The main advantages of doing so are that it would reduce build times (since only one binary would need to be generated), it would answer the question of where the binaries would be stored (we could use the existing bucket, though only some of the binaries pushed there would include the flask server), and it would keep all of the InVEST-related CLI entry points all in one place in a single binary.  That last point could be a downside too, if we wanted to hide the flask server from people who are running InVEST from the CLI.  There are probably other downsides there as well that I'm not thinking about.

I think this is probably a great idea. It would simplify things a bit on the electron side as well, to just have one exe binary to think about. Doing this would mean developing the CLI endpoint in this PR instead of modifying this repo's `invest.spec` script.

**Comment by phargogh** [comment]
> So removing the Qt UI stuff probably shouldn't happen right away.
👍 

> It would simplify things a bit on the electron side as well, to just have one exe binary to think about.  Doing this would mean developing the CLI endpoint in this PR instead of modifying this repo's invest.spec script.

Yep, that sounds right to me, and I'm glad that it would simplify things a bit on the electron side as well!

**Comment by emlys** [comment]
I think this was completed in natcap/invest-workbench#70.
