### ISSUE TITLE
InVEST User Survey

### ISSUE THREAD

**Issue by emlys** [natcap/invest#357]
It would be interesting to do a casual survey of InVEST users to get feedback on how they're using the software and what features are/n't important. We could do an anonymous survey through Google Forms and distribute it on the forum, to partner organizations, and to email lists from past workshops.

Some ideas of questions to ask (feel free to add on to this list):

- Which InVEST models have you used ever/in the past year? (checkboxes)
- Of those, which did you run successfully with your own data?
- Did you use the results in published research?
- What OS and InVEST version do you use?
- Make a list of features we are considering adding and ask them to check all that would be useful to them
- Ask for free-form suggestions of other features to add
- Make a list of common problems users encounter (finding suitable data to run the model, getting data to pass validation, understanding the user's guide, getting unexplained errors, etc.) and ask them to check all that were obstacles to them using InVEST
- Have you ever written a script interacting with the InVEST python API? What did it do?

**Comment by phargogh** [comment]
Like with any project, it'd be useful to hone in on the problem we're trying to solve, both to help direct the questions we ask and to justify the effort needed to conduct a survey and to analyze the results.  Is there a decision that we can't make right now that we would be able to make with survey responses?

> * Did you use the results in published research?

Let's be sure to talk with Lisa about some of her prior work with the InVEST publications database if we include this question in an InVEST user survey.  This could end up being a useful way to crowd-source InVEST publications!

**Comment by davemfish** [comment]
* Have you ever used the "Save Datastack" feature? 

I'm interested in this for a few reasons:
* There's an open issue about missing input files that are only referenced in other CSV inputs #342 
* We haven't yet developed the workbench interface to this feature https://github.com/natcap/invest-workbench/issues/11
* Is there another solution we should work on instead (e.g. an ecoshard-based approach to data-sharing)

**Comment by phargogh** [comment]
* **How many people in your office also use InVEST?**

We've previously discussed the possibility of distributing the computational work of InVEST across multiple computational nodes, such as across the local network (turning people's workstations on a LAN into an ES modelling cluster) or across nodes in a datacenter.  If there's only one person running InVEST in an office, they might be less likely to need heavy compute power, and also less likely to have other nodes in the office available to run an InVEST client.

* **Have you used the InVEST python package?  If so, what sort of problems were you able to solve with the python package that you weren't able to solve with the InVEST user interface?**

I'm interested in this because:

* Usage logging only comes from InVEST modelling runs done through the Qt UI
* This might help us gauge the nature of the problems that people are experiencing that could be common enough to implement in the workbench

**Comment by emlys** [comment]
A while back, we tried posting a brief survey on the forum and got like 7 responses
