### ISSUE TITLE
make env failing on scipy

### ISSUE THREAD

**Issue by emlys** [natcap/invest#388]
Observed on macOS, release/3.9.
The `make env` command is failing. For some reason pip is trying to build numpy from source, resulting in errors because of missing header files etc. 
The quick fix may be to install scipy/numpy from conda with nomkl (probably good to use conda when possible anyway). But it would be nice to know why this is happening.

**Comment by dcdenu4** [comment]
I'll add that  `make env` on Windows also doesn't work. But mostly because it's a bit out dated from the changes I made when moving our github action workflows to be `conda` based. If we assume the user needs `conda` installed, then `make env` should be the same for both MacOS and Windows I would think. 

I feel somewhat responsible for the Makefile being slightly broken in general because I chose not to refactor it when adjusting Makefile stuff for the github actions workflows... So I'm inclined to assign this issue to myself.

**Comment by emlys** [comment]
Turns out that this was because python3.9 is now the latest/default version for new conda envs. Specifying `python=3.8` in the `conda create` command solves the problem! This fix is going into the final release branch.

**Comment by dcdenu4** [comment]
Oh interesting. I guess once InVEST 3.9 goes out we should start Python 3.9 support! It is annoying that our version numbers are so close at the moment.

**Comment by dcdenu4** [comment]
Following up with **Windows** side of `make env`:

I was having a hell of a time activating the env and installing natcap.invest in the command:
`$(BASHLIKE_SHELL) "$(CONDA) activate ./$(ENV) && $(MAKE) install"`
I would get errors about `scipy` or `gdal` or `xlwt` or `psutil` about not finding versions that satisfy `natcap.invest`. When activating the environment and looking at `conda list` everything seemed to be in order. Calling `make install` from within the environment completed successfully. 

I tried a bunch of workarounds like `.ONESHELL:` and using ` ; ` to extend commands in the same shell, but could not get anything to take. Thus this is what I settled on for the Makefile:
```
# Python conda environment management
env:
  $(PYTHON) ./scripts/convert-requirements-to-conda-yml.py requirements.txt requirements-dev.txt requirements-gui.txt > requirements-all.yml
  $(CONDA) create -p $(ENV) -y -c conda-forge python=3.8 nomkl
  $(CONDA) env update -p $(ENV) --file requirements-all.yml
  @echo "----------------------------"
  @echo "To finish the conda env install:"
  @echo ">> conda activate ./$(ENV)"
  @echo ">> make install"
```
So instead of an all in one we now have two simple steps:
1) `make env`
This will end with : 
```
done
#
# To activate this environment, use
#
#     $ conda activate C:\Users\ddenu\Workspace\NatCap\Repositories\invest\env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

----------------------------
To finish the conda env install:
>> conda activate ./env
>> make install
```
2) do as above message says.

**Comment by emlys** [comment]
This was fixed [here](https://github.com/natcap/invest/commit/67196f8523f5e2cae5b39a0c57961ffe3110ca6c)
