### ISSUE TITLE
InVEST 3.9 Release Issues

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#402]
I did a sweep of the InVEST 3.9 pre release and came across the following issues when running each model with the sample data and examining the output.

- [x] **Forest Carbon EE** has an `OverflowWarning` at some point in the log output. **Emily**
- [x] **Forest Carbon EE** raster output looks bugged where `nodata` should be?
- [x] **DeliniateIt** Stacie has some comments in a Slack post that might be worth addressing.
- [x] **DeliniateIt** has output watershed that might be overlapping or multipolygon? Is this right? **Emily**
- [x] **Forest Carbon EE** local doc link is broken. 
- [x] **SDR** Stacie says she got a local docs error from this model, that I did not get.
- [x] **Validation** `validation.timeout` messages are more appropriate as `debug` than `info` level 
- [x] ~~**HQ/CBC** should these models have a note in Data Needs about the updated inputs? Should they indicate 3.9+?~~ I think we agree that this isn't necessary since the UG is versioned along with invest (dave)
- [x] **InVEST** is there a way to have the Windows items be alphabetical and CBC grouped? ( Dave? )
- [x] **HQ** add clarification to UG around Threats and Sensitivity table ( Doug )
- [x] **Wave Energy** remove 3.0 Beta comment in UG.
- [x] **DeliniateIt** has has number indentation issue in UG. **Emily**
- [x] **Crop Production Reg** `soybean reg prod` raster looks bugged with values `-1.79e308` to `1.79e308`
- [x] **Coastal Vulnerability** `population` column / field has values `-1.3106e+39`, is that right?
- [x] **SDR** has output raster with small `sed_dep` value... might be worth checking
- [x] **SWY** has output raster with `-1.05e-05` value... might be worth checking
- [x] **CV, DelineateIt, HRA, Urban Flood** all seem to suffer from `VirtualXpath` dumps during validation in console output. **Emily**
- [x] **GLOBIO** has outputs that look like artifacts or streaking that could be caused by a bug
- [x] **Scenic Quality** output looks not quite right, but I don't know what it should look like?  **James**

If someone would like to look into any of these issues, feel free to edit this with your name at the end of the line.

**Comment by emlys** [comment]
I'm leaning towards saying that the multipolygon Delineateit output is expected. I ran with both the `outlet_features.shp` and with the new 'detect pour points' option. With 'detect pour points' I get 1 pour point (expected because the DEM is all one watershed) and there is one watershed polygon covering the whole DEM area. Using `outlet_features.shp` instead I get 4 small watershed polygons, one around each `outlet_features` point. I think because the `outlet_features` points are _not_ pour points, it makes sense that each one has its own mini-watershed that doesn't encompass the whole thing. Does that make sense?

**Comment by emlys** [comment]
Just pushed a fix for the delineateit UG issue. Sneaky line breaks!

**Comment by emlys** [comment]
While testing the Delineateit issue, the model run kept hanging. Setting n_workers to -1 solved the issue. So I guess there's another multiprocessing race condition in there somewhere... yay 🙃

**Comment by emlys** [comment]
The VirtualXPath issue only is happening in gdal>=3.1.3. I'm going to pin gdal==3.1.2 for the release

**Comment by davemfish** [comment]
False alarm re: the Crop Production issue. Pasting my explanations from slack:

I just looked at the Crop Production issue mentioned above. Seems there are no soybean pixels in the sample data LULC. I assume that's by design. The csv lookup table is
```
crop_name,lucode
barley,1
wheat,20
soybean,1000
```
And the `landcover.tif` is a Byte raster - i.e. there are no 1000s.

More importantly, the crop production model is writing an output raster full of nodata, which seems like exactly what it should be doing in this case. The -1.79e308 to 1.79e308 values is just QGIS failing to provide a useful legend for a Float32 raster. All the values are actually -1 , which is correctly set as nodata.

**Comment by davemfish** [comment]
SWY sample data outputs look good based on my interpretations of the UG & forum conversations.

**Comment by davemfish** [comment]
The very tiny SDR value is essentially equal to 0, furthermore it doesn't actually exist in the raster - which has a min of 0 - but shows up in QGIS, and maybe is some sort of estimate of the minimum value that gdal/QGIS is doing on the fly.

**Comment by phargogh** [comment]
SQ looks OK to me!  There are some visual artifacts (a sort of stepped look) in the viewshed results which is consistent with the DEM which also has that sort of stepping.  So given the sample inputs, the outputs look good to me!  I'll mark it off the list.

**Comment by dcdenu4** [comment]
Okay, I have a PR in for GLOBIO, but I realize I haven't updated that sample data yet. So still need to do that.

**Comment by dcdenu4** [comment]
That's a lot of great check marks off the checklist! I am going to consider this closed. But leave it open in case anyone has some cleaning up to do in the form of making new issues from things that were discussed but decided on not being handled here directly.
