### ISSUE TITLE
Pandas 1.2.1 causing tests to fail

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#450]
When putting a PR together I noticed that some tests were failing that were not failing before. Luckily the PR was about better dependency transparency! Looking at the diff between conda envs used between the successful workflow and the now failing one, I saw:

```
85c85
< pandas=1.2.1=py38h4c96930_0
---
> pandas=1.2.0=py38h4c96930_1
```

Tests failing:
```
=========================== short test summary info ===========================
FAILED tests/test_utils.py::ReadCSVToDataframeTests::test_non_utf8_encoding
FAILED tests/test_validation.py::CSVValidation::test_csv_not_utf_8 - TypeErro...
```

Looking at Pandas 1.2.1 change notes they list:
> Fixed regression in read_csv() and other read functions were the encoding error policy (errors) did not default to "replace" when no encoding was specified (GH38989)

Output of the returned `pandas.df` (that didn't error because of now replacing) from `test_non_utf8_encoding`
```python
  header  Unnamed: 1
0    f��         NaN
1    bar         NaN
```
I can't remember how the discussion went about if we liked this replacing approach or didn't...

**Comment by dcdenu4** [comment]
Prior convo here: https://github.com/natcap/invest/issues/428

**Comment by davemfish** [comment]
Oh, very interesting. Kinda makes me wish we did just wait for the bugfix release before updated pandas 1.2. Anyway, I think we felt like it's best to let pandas decide what to do here (replace or raise exception). I didn't realize they thought of this as a regression, I thought maybe they changed their mind on what to do. Anyway, I think we ought to update our tests, or basically revert them back.

Also, I'm gonna mark this as critical since it's causing CI failures for everyone, and we discussed using that label for exactly this case.
