### ISSUE TITLE
BUILD: sampledata archives do not include the json datastack files

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#525]
Sampledata archives made during the build process exclude the json datastack files. Instead, the jsons are copied over to the installer by the custom NSIS installer script. I guess the idea there is that the json files should be included in all installations, even when the user chooses not to download any of the sample data? I guess there's no harm in that, but those json files are of limited use without the associated data.

The workbench expects all invest resources to be found in the GCS bucket configured in `package.json: invest`, and right now the json files aren't there.

So, we could change the `make sampledata` targets to include the json files in the zip that is deployed to GCS during `make deploy`.  Workbench users won't get the json files unless they also choose to download the sample data. Is that okay?

**Comment by phargogh** [comment]
I am 100% in support of including the InVEST JSON files in the sample data zipfiles rather than distributed by the installer.

If memory serves, that's where they were located when we first created the datastacks, but there was some complicating factor I don't remember and we moved them out to the top level.

Including the JSON files in the sample data archives will also mean that anyone who goes to download the archives after the fact will _also_ get the json files.  At the moment, they'd only be included in the NSIS installer, which isn't ideal.

I'd also be in favor of being sure that the model names are included in the filenames of the sample files, but having them in the model-specific directory would help associate that parameter set with the model anyways.

**Comment by davemfish** [comment]
Thanks @phargogh . There's a couple options here. I wasn't necessarily thinking of moving the JSON files relative to their place in their git repo, though we could. I was mainly thinking of making sure they get zipped in the "one big zipfile" target that zips everything and is deployed to GCS. 

But that doesn't solve the problem of not getting the JSON files when downloading an individual model's zipfile. So I like your idea of moving the JSON into the model folders. It just means editing all the relative paths in those files.

The other thing to figure out is the association between sample datastacks and models. Right now the folder/filenames aren't a direct match to model names. They could be. Or we could think about keeping some sort of mapping that the workbench can use so it always knows which datastacks are available for which models.

**Comment by davemfish** [comment]
After some experimenting, it seems that invest installations are unaware of the existence of the sampledata json files that come with the installation. Model forms load inputs from previous runs (data cached in `ini` files) but even when those data don't exist, the model does not try to load the sampledata json.

I'm not sure if that's a bug - I thought those datastacks might load by default when there is no previous run. But it's actually convenient for this issue. I think it means we can safely re-organize the git-lfs repo to move the json files into their respective model folders without disturbing invest UI behavior.

**Comment by davemfish** [comment]
`invest/scripts/invest-autovalidate.py` will need to be updated to expect a new directory structure.
