### ISSUE TITLE
Mysterious CV test failure

### ISSUE THREAD

**Issue by emlys** [natcap/invest#597]
One CV test is failing on my branch: https://github.com/natcap/invest/pull/555/checks?check_run_id=3174860834#step:12:2380 The error is not related to the pygeoprocessing/gdal update.
```
E   AssertionError: DataFrame.iloc[:, 2] (column name="R_hab") are different
E   
E   DataFrame.iloc[:, 2] (column name="R_hab") values are different (25.0 %)
E   [index]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
E   [left]:  [4.05, 5.0, 4.05, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.7999999999999998, 5.0, 5.0, 5.0, 5.0, 5.0]
E   [right]: [4.05, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.7999999999999998, 5.0, 5.0, 5.0, 5.0, 5.0, 4.05, 5.0]
```
I can reproduce this locally on my branch and `main`. I traced it back to 69c34e17 where the test data commit hash was updated. Why has the test been passing on main all this time but failing locally and on my branch?

**Comment by emlys** [comment]
It seems the points are getting created in a different order. I added some print statements and the results are different locally vs. on github actions:
```
Local:
R_hab of feature with shore id 0, fid 1: 4.05. WKT: POINT (265195.911887124 5465342.35997848 0)
R_hab of feature with shore id 2, fid 3: 4.05. WKT: POINT (376479.981953834 5383636.19727002 0)
R_hab of feature with shore id 14, fid 15: 5.0. WKT: POINT (268404.529677045 5479539.25647222 0)

GHA:
R_hab of feature with shore id 0, fid 1: 4.05. WKT: POINT (376479.981953834 5383636.19727002 0)
R_hab of feature with shore id 2, fid 3: 5.0. WKT: POINT (344736.257952145 5411347.42870694 0)
R_hab of feature with shore id 14, fid 15: 4.05. WKT: POINT (265195.911887124 5465342.35997848 0)
```
It looks like the same R_hab values go with the same point coordinates, but the shore ids are different.
If we expect points to be created in the same order every time, this is a bug. If not, the test should be updated to allow any ordering of the same points.

**Comment by emlys** [comment]
When we iterate over a shapely multipolygon ([line 662](https://github.com/natcap/invest/blob/be69c1523f788d0336d0d64fac90be713c7637f0/src/natcap/invest/coastal_vulnerability.py#L662)), it seems the order is not guaranteed. When the two landmasses in the `test_complete_run` test case go in one order, the tests pass. I'm not sure why the order seems to stay consistent within one context (always passing on `main`, always failing on #555 and locally for me). 

Any opinions on whether shore points should always be created in the same order? On one hand, it doesn't really matter. On the other, it could confuse users if the order changes from one run to another.

**Comment by phargogh** [comment]
> Any opinions on whether shore points should always be created in the same order?

I don't think shore points should need to be constructed in the same order because the programming model for vectors is a database: each feature is a discrete collection of attributes that also happen to have a spatial geometry.  The creation order of records and order in which they are stored should be up to the underlying file format and/or data provider.

So for us for this test, I think it would be a perfectly reasonable thing for the test to sort the R_hab values from the test and regression data before comparing them against what's expected.

>I'm not sure why the order seems to stay consistent within one context 

Yeah, this is weird indeed!  Offhand it looks like the GDAL version installed in each might be the culprit ... one is using GDAL 3.2.0, the other 3.2.2 if I'm looking at the right logs right now.  Maybe something changed in the GeoPackage implementation between those versions?
