### ISSUE TITLE
Clarification of SDR "sediment retention" and "sediment retention index"

### ISSUE THREAD

**Issue by emlys** [natcap/invest#601]
SDR provides two sediment retention outputs, and it's not clear how to interpret them. @newtpatrol says:
> Regarding sediment retention and sediment retention index, YES that should be clarified. I still do not understand the difference, and maintain that if we're providing something that is an "index" it should be on a scale of 0-1. Given that I don't currently understand the difference, I'd prefer to have a single sediment retention index provided (not sed_retention, but an index), on a scale of 0-1, which makes it clear that it is not to be interpreted quantitatively, which we've had to deal with on the forum many times.

Need to figure out what these outputs mean, and if that's not possible, consider deprecating one/both, and/or replacing with a 0-1 index (would need science team engagement).

**Comment by dcdenu4** [comment]
I have some context for these from Rich somewhere. I'll try and dig out our conversation about them.

**Comment by dcdenu4** [comment]
See Rich's reply to this user here at the end:
https://community.naturalcapitalproject.org/t/interpreting-sdr-results/1649/9

> I suspect you actually want the downslope sediment deposition raster. It gives a good estimate of where sediment that has run off from a pixel has been retained downstream by the vegetation on the landscape: SDR Sediment Deposition User’s Guide Section 1.

>The sed_retention_index.tif and sediment_retention.tif analyses were left over from very old versions of InVEST that was our only “what is the benefit” scenario at the time and before we derived the sediment deposition analysis. In reality, comparing the current state to a state where the entire landscape is bare exposed dirt isn’t really useful. I suspect in all practical cases folks, and you too, will want to use sediment_deposition_[Suffix].tif in lieu of either of the sed_retention rasters.

**Comment by newtpatrol** [comment]
Sediment deposition does seem like a more realistic "service" than the way we do sediment retention. Retention did kinda sorta have a use, it basically created a scenario of losing all vegetation and comparing the results. But those results weren't quite what we typically recommend for evaluating service with SDR - create an actual likely scenario and take the difference in sed_export, which is a more holistic approach. And boy has it been tedious trying to caveat the use of sed_retention over the years.

Given the many related forum topics, since we're chewing on this, we might also figure out how exactly to recommend using sed_deposition. If it is the amount of sediment from upslope that deposits on a pixel, it does not take into account retention on the pixel itself. So if people want to get a full picture of the sediment deposition service, should we recommend adding some other on-pixel piece of SDR to sed_deposition? Looking at the equations, I'm not sure which one would be used (maybe it's too early in the day for me to attempt math...) and maybe it's not really necessary, just thinking out loud. Whether deposition should stand alone for service, or some post-processing is needed, we should be clear about that and put it in the User Guide.

Also given past forum posts, people have and will ask if they should be able to do things like sum sed_export and sed_deposition and get USLE, and I don't think we've been able to provide a definitive answer. Is this a good time to ponder that as well?

~ Stacie

________________________________

**Comment by emlys** [comment]
This was fixed in #1016
