### ISSUE TITLE
UCM test: different results when re-run in same workspace

### ISSUE THREAD

**Issue by emlys** [natcap/invest#615]
To reproduce:
1. Edit the test `test_ucm_regression_factors` so that `args['workspace_dir']` is not temporary: `args['workspace_dir'] = '/Users/emily/Documents/ucm-test2'`
2. Run the UCM tests (all pass)
3. Run the UCM tests again (now `test_ucm_regression_factors` fails with an error: `AssertionError: 10560639.842782581 != 3520213.280928277 within 4 places (7040426.561854305 difference) : avd_eng_cn should be close to 3520213.280928, actual: 10560639.842783`

You should be able to re-run any model in the same workspace and get the same result, so it's concerning that the aggregate results are different.

**Comment by phargogh** [comment]
Working on this in `bugfix/615-ucm-tests-different-on-re-run`.

**Comment by phargogh** [comment]
So far, debugging this has been a wild ride.

The main thing that I've noticed is this: so long as we're in the same InVEST run, the values will be what they should be.  The one I keep testing is what's being tested in the UCM test Emlily mentions, `adv_eng_cn`.  After the function runs, the value of this field in feature 1 is `3520213.2`, as it is expected to be.  BUT WAIT!  Once the process exits, if I inspect the field of this feature again (doesn't matter how: python, `ogrinfo`, QGIS), the value of this field is _always_ 3x what it should be.

This appears to be a GDAL bug and I'm working on a way to reproduce it.

**Comment by phargogh** [comment]
* Not an issue with the field name -- renamed field from `avd_eng_cn` to `foo`, no change in behavior.
* Happens on Debian 11 as well, just with slightly different numbers (running on InVEST 3.8.7 to avoid GDAL version conflicts using current GDAL on debian:stable)
* If I run the model twice in the same test?  Same results.

**Comment by phargogh** [comment]
Wow, debugging this has been _super_ interesting.

All of my previous comments about what I was trying were unfortunately in the _completely_ wrong universe.  GDAL is fine.  The reason the numerical values are 3x what they should be is that the test in question (`test_ucm_regression_factors`) runs UCM _twice_, and the second time it's using an energy consumption table that uses a multiplier of 3.  So that explains why the results are so numerically different.

What's NOT explained by that table being there is why `taskgraph` continues along and thinks that the tasks are OK as-is.  Part of this issue is resolved by upgrading to the latest rev on the `taskgraph` `main` branch because there's a bug in `taskgraph` that's preventing the correct hash algorithm from being used.  But even after upgrading to the latest on `main`, there's still a problem: our tests run too fast for `isclose()`/`mtime` to be a useful comparison.

It turns out that, because we're running these tests as quickly as we are 4 times across 2 successive `pytest` runs, the two task runs are, in fact, numerically close as tested by `math.isclose` and so `taskgraph` thinks that the task has been precalculated with it for _sure_ has not.

So this is ultimately a bug in `taskgraph`, and I'll be following up about that over here: https://github.com/natcap/taskgraph/issues/70

**Comment by phargogh** [comment]
The solution to this issue is now pending https://github.com/natcap/taskgraph/pull/75, and then ultimately a taskgraph release: https://github.com/natcap/taskgraph/issues/73

**Comment by emlys** [comment]
Closed in #742
