### ISSUE TITLE
Build sphinx API docs as part of regular builds

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#62]
Right now, we can only test issues with the API docs and its requirements by either:

1. building them locally or
2. pushing something to `natcap/invest/master` and then waiting for the readthedocs build to fail.

Can we test the sphinx build in a reasonably-simulated RTD-like build job?

**Comment by phargogh** [comment]
Alternatively, we can just make sure that build failure emails go to the team.

**Comment by emlys** [comment]
RTD offers an option to build on pull request, which is neat. It integrates with the PR checks so that the build status displays alongside our actions workflows. There are some downsides though:
* As far as I can tell, it's only triggered by new commits to the PR. Unlike in Github actions, you can't click a button to rerun the job.
* The RTD build page is arguably uglier and harder to use than Github's: https://readthedocs.org/projects/invest/builds/12465096/

The benefits are that it's really easy to set up (just check a box in the RTD admin settings), and it should always be the exact same build environment and process.

If we want to replicate the RTD build process using Github Actions, that should be possible using the RTD build docker container: https://hub.docker.com/r/readthedocs/build/
