### ISSUE TITLE
Create a mask raster for SDR/NDR areas that don't drain to stream

### ISSUE THREAD

**Issue by emlys** [natcap/invest#621]
As discussed in #609, some SDR/NDR outputs now have `nodata` in areas that don't drain to a stream. @newtpatrol has suggested that:
> these pixels receive a distinctly bogus value like -9999, so they'd be really obvious to people, and they wouldn't have to pour through their inputs to see what's causing NoData in the output

This would clarify that nodata areas come from an input, while areas with `-9999` are undefined because they don't drain to a stream.

**Comment by davemfish** [comment]
In other words, is the suggestion to have two distinct values representing nodata? That's challenging because only one of them can be the official nodata value recognized by GIS software. So if it's desirable to 1) have a desktop GIS automatically hide the nodata during display or 2) have a geoprocessing tool like zonal stats automatically ignore nodata in summaries, then we probably want to stick with a single nodata value.

I understand wanting to distinguish the origins of the nodata, but maybe it's best to resort to a different option, like writing out a separate mask raster representing the areas that don't drain?

**Comment by dcdenu4** [comment]
I think the intended effect is to just have -9999 pixel values ( not nodata ), where a pixel doesn't drain. I think we discussed this as a possibility because of the point Stacie brings back up of: I'm a confused user who doesn't understand why my outputs are changing in "size" (more nodata holes vs less nodata holes) when I use different flow accumulation thresholds.

> but maybe it's best to resort to a different option, like writing out a separate mask raster representing the areas that don't drain?

This is a good idea Dave. I'm not sure how easy it is to implement, but another visual output certainly could help people wrap their heads around what they are seeing and why. 

**[ I *almost* kept these thoughts to myself. Feel free to ignore. ] [ op-ed ]**
I think there's an interesting tradeoff here between demanding a sound structural hydrology model and providing useful / usable outputs to users. The pour points solution as it was, attempted to give a "best effort" handling of pixels that did not drain to a stream directly ( and thus possibly overestimated results ), but did provide defined outputs for a study area. The nodata solution as it is, attempts to keep a sound hydrology model, saying if we can't know for sure where these pixels would drain to and the distance we will punt on returning values at all ( possibly underestimating results ), at the cost of a user not having defined outputs for a study area. I don't know what the "correct" solution is here, but I wonder if InVEST users with rough real world data can be *expected* to have their inputs set up perfectly for a hydrologically bounded domain such that they don't encounter nodata gaps in their study area. If not, maybe the pour points approach is the simpler path.

**Comment by davemfish** [comment]
> I think the intended effect is to just have -9999 pixel values ( not nodata ), where a pixel doesn't drain. I think we discussed this as a possibility because of the point Stacie brings back up of: I'm a confused user who doesn't understand why my outputs are changing in "size" (more nodata holes vs less nodata holes) when I use different flow accumulation thresholds.

Yeah I get this perspective. I just think this approach trades that confusion for the confusion of "why do I have all these -9999s in my raster?" And "Why does the coverage of those -9999s change with different flow accumulation thresholds?" -- so essentially the same points of confusion either way.

My opinion is that if we set these pixels as nodata, they stay hidden by default and at least some users will never have to think about any of this. If we use a non-nodata value (-9999), then all users will at minimum have to ask, what does -9999 mean? And then they will have to do a little bit of extra work to make maps or summarize their results, etc.

**Comment by phargogh** [comment]
We talked about it today and decided that it would be useful to produce a mask raster identifying which pixels are not draining to a stream.  This could be a helpful check for whether their inputs are lining up and/or the DEM doesn't have anything going on.

**Comment by phargogh** [comment]
OK to push back if we don't get it done by the release.

**Comment by newtpatrol** [comment]
Providing a mask raster seems like a great option, since it would be a separate layer, and not muddy the results otherwise. Would the non-mask output still get NoData values? We'll need to add text to the User Guide explaining what it means and how to use it.

**Comment by dcdenu4** [comment]
@newtpatrol 
>Would the non-mask output still get NoData values?

Yep, I think the idea is that the mask would have NoData values everywhere except where pixels did not drain to a stream. Although this will end up just being all NoData in a lot of cases. Maybe it makes more sense to have a 0 and 1 binary output with the raster being "clipped" (didn't want to say masked again) to the LULC. Something to consider!

**Comment by phargogh** [comment]
Working on this in `feature/621-create-mask-ndr-sdr-drainage`.

- [ ] Implement
- [ ] Test
- [ ] Update SDR user's guide
- [ ] Update NDR user's guide

**Comment by phargogh** [comment]
See https://github.com/natcap/invest.users-guide/issues/53 for the UG PR.  Changes will be draft-PRed in shortly.

- [ ] update the UG hash once the UG changes are included in both SDR and NDR chapters.
