### ISSUE TITLE
Revisit how we package and use non-python files

### ISSUE THREAD

**Issue by emlys** [natcap/invest#644]
Thinking about this because I needed to add a translation message catalog file to the `natcap.invest` package.
https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html

We currently use both `MANIFEST.in` and `package_data`. [This article](https://www.remarkablyrestrained.com/python-setuptools-manifest-in/) argues for replacing `MANIFEST.in` with a list of checked-in files that you can get from `setuptools_scm`, which we already use for something else. [The setuptools docs](https://setuptools.readthedocs.io/en/latest/userguide/extension.html#adding-support-for-revision-control-systems) detail that option.

- Do we need to use both `MANIFEST.in` and `package_data`?
- Would it simplify things to use only one of them?
- Should we be accessing package data using the setuptools `ResourceManager` API like they [recommend](https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html#accessing-data-files-at-runtime), instead of `__file__`? This is relevant for the existing `reporting_data` and also for translation catalogs.

**Comment by phargogh** [comment]
Man, python's data file management systems are _messy_.

In my experience (and I never fully understood this), `MANIFEST.in` has been the most reliable way to ensure that files would end up in the source distribution.  This did change (silently) when we started using `setuptools_scm` for versioning, as now the source distribution contains files unrelated to the python installation.  Not necessarily a bad thing, but unexpected.

The (blog post)[https://www.remarkablyrestrained.com/python-setuptools-manifest-in/] you link makes a really interesting, opinionated decision that an `sdist` should be a copy of the checked-in source code.  I'm not completely sure I agree.  If a user runs `pip install natcap.invest`, should they receive the NSIS installer build instructions?  These are smallish files so the resulting archive isn't huge, but this is something that we've never explicitly decided on for the project and really should.

> Do we need to use both `MANIFEST.in` and `package_data`?

Based on the documentation, it seems like maybe `MANIFEST.in` is no longer needed, so long as we're using an SCM, which we are!  Personally, I'd _love_ to see `MANIFEST.in` go away and have needed configuration be defined in `setup.py` to keep as much of the distribution information in a single place as we can.

> Should we be accessing package data using the setuptools `ResourceManager` API like they recommend, instead of `__file__`? This is relevant for the existing reporting_data and also for translation catalogs.

Maybe?  We have 2 challenges to be wary of in trying this out:
1. We may also need to update file locations in our pyinstaller binaries.  The fact that we're using pyinstaller distributions messes with the usual filesystem layout Python is used to, and the approach we have right now in `src/natcap/invest/__init__.py` was at one time the recommended way to determine paths relative to pyinstaller's compiled binary.  It looks like they now seem to recommend a [`pkgutil`-based approach](https://pyinstaller.readthedocs.io/en/stable/spec-files.html?highlight=files#using-data-files-from-a-module), so maybe support for package data has been improved?  It does [look like they've updated things to no longer require `sys._MEIPASS`](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html?highlight=_MEIPASS#using-file).
2. `natcap` is a namespace package, which means that the `ResourceManager` API might not behave as expected since different parts of the namespace can be installed in different places.  From the [`ResourceManager` API docs](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access): 
   > Also, you should not use use a namespace package name, because a namespace package can be spread across multiple distributions, and is therefore ambiguous as to which distribution should be searched for the resource.

The last time we worked with `gettext` translations in a python application (OPAL) it looks like we [programmatically built up the package data structure](https://github.com/natcap/opal/blob/bugfix/STATICMAPS-3379-skip-bare-paved-scenarios/setup.py#L616) with the compiled message catalogs and then [relied on `__file__` to locate them at runtime](https://github.com/natcap/opal/blob/bugfix/STATICMAPS-3379-skip-bare-paved-scenarios/src/natcap/opal/i18n/__init__.py#L17).
