### ISSUE TITLE
Look into Habitat Quality Range Issue

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#646]
From [Stacie on Slack](https://stanford-natcap.slack.com/archives/CECFUU1DW/p1631549087037100):

> Hey y'all, there's [yet another post on the forum](https://community.naturalcapitalproject.org/t/habitat-0-01/2173) about the fact that HQ generally gives outputs that are all at the very high end of the 0-1 range. This did not used to happen, something changed in the last couple years or so that caused this, and it's consistent. It even happens with the sample data, I've seen people report it on the forum, and I've seen it when working with external groups on their projects. Usually, the habitat degradation values have a much more reasonable spread, but the quality values fall between 0.9 and 0.9999999. Yes, we can tell people to fuss with the half-saturation constant to make it somewhat better, but that never used to be needed to get initial values that actually represented a reasonable spread between 0 and 1, and it's a very unsatisfying/opaque response to this unintuitive behavior. I've noted this several times in the past, and am again today, since it's once again coming up on the forum. I actually avoid teaching HQ for this reason, the results are confusing, and I have no explanation for why they're that way.

Anne says that Jade is the science lead on this, so she might be able to dig into this a bit.

But also, we should bisect this and try to see where the change was introduced and why it's happening.  Is it just an issue with the default half-saturation constant?

**Comment by dcdenu4** [comment]
Here is a lengthy thread from the forums from May 2020 outlining this frustration as well:

https://community.naturalcapitalproject.org/t/habitat-quality-output-raster-looks-strange-and-output-values-have-no-intermediate-values/977/15

My historical memory on this is a bit vague, but I tend to always remember this being the case. Where the quality outputs would be not very useful on the first run but produce more variation on the second run when updating the half saturation constant accordingly. Honestly, we could just do this step in the model without making the user run it twice.

I definitely would be curious to look back and find the version of InVEST where Stacie thinks this wasn't always the case. It sounds like 3.4.4 -> 3.7.0 might be an interesting range to investigate. Pygeoprocessing and the convolution functions will be important to track as well.

**Comment by dcdenu4** [comment]
# Current Behavior (3.9.2)
Default half saturation constant: 0.05

# InVEST 3.7.0 Behavior
Default half saturation constant: 0.5

**Comment by dcdenu4** [comment]
@newtpatrol I just ran some old HQ models and noted the result. At least with the sample data I didn't find any differences in default output. With 3.9.0 and later we switched the default half saturation to to be 0.05 instead of 05, because 0.05 is basically half the degradation score you would get. This way running with the default sample data and default half saturation constant, you get some contrast in habitat quality output. 

Like I mentioned, it might make sense to take this option away from the user entirely. That is, in the model use half of the max degradation output as the input to habitat quality output directly. 

I'd be curious your thoughts on this or anything I'm missing.

**Comment by newtpatrol** [comment]
Thanks for looking into this again @dcdenu4, and sorry to be such a pain about it. I'm still unclear as to why the previously recommended half-saturation constant of 0.5 worked fine with old versions, but 0.05 is needed to get a good spread for newer versions, it makes me think that some underlying degradation/quality math changed. A value of 0.5 indicates that you're getting degradation scores that are an index typically between 0-1, not an index that's typically 0-0.1. Maybe it's ok that the degradation scores are so small, and I need to stop thinking of it as a 0-1 index when it's not?

That said, I see what you mean about how a half sat value of 0.05 makes a big difference, and the results look much more interesting. If you're sure that the underlying math is fine, I'll shut up about it and use 0.05. 

As for the possibility of taking away the option from user input, I'm pretty sure that most everyone uses the recommended default and doesn't think about it further. If we always recommend to set it to half of the degradation score, then calculating and applying that automatically in code seems reasonable. However, since it obviously plays a huge role in the result values, I might suggest making half sat an optional input for people who want to fuss with it, otherwise it's automatically calculated.

**Comment by dcdenu4** [comment]
@newtpatrol 
>I'm still unclear as to why the previously recommended half-saturation constant of 0.5 worked fine with old versions

Do you mean older versions than 3.3.0, like the ArcGIS versions? I can keep going back further, but it looks like the behavior from at least 3.3.0 onward has not changed.

>it makes me think that some underlying degradation/quality math changed. A value of 0.5 indicates that you're getting degradation scores that are an index typically between 0-1, not an index that's typically 0-0.1.

This is a good point. I believe the reason we're not seeing a 0-1 index response for Degradation is because we are using a convolution approach to degrade threats over distance. This could be the change that really separates the "old" vs "new" versions you're thinking of. What ends up happening is that the impact of each threat (`i_rxy` in degradation equation) is a pretty small number even if the distance is very small (meaning the pixel is close to the threat). Back in the day Rich convinced me that this was the right way to go and better (more realistic) in most regards. But we could look at revisiting this.

**Comment by dcdenu4** [comment]
This has been worked through and fixed. See:

- https://github.com/natcap/invest/pull/1159
- https://github.com/natcap/invest/issues/1104
