### ISSUE TITLE
setup.py commands deprecation

### ISSUE THREAD

**Issue by emlys** [natcap/invest#717]
I was looking at the `setuptools` repo and noticed a recent commit message _"Deprecate setup.py install and easy_install."_ It seems that `setuptools` is slowly deprecating all direct calls to `setup.py` commands - though this isn't well documented or announced anywhere. Need to investigate further and determine if we need to make any changes.

Related setuptools issue: https://github.com/pypa/setuptools/issues/917
Blog post: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

I routinely use `setup.py` install, though our `make install` command already uses `pip install` which may be the correct alternative. Our `setup.py` also provides the `build_ext` command.

**Comment by phargogh** [comment]
Well _this_ is an interesting break from precedent ... PyPA stepping up their orthogonality game!  I'm particularly curious what we'll need to do for our cython files to get them to work with what they're recommending.

**Comment by phargogh** [comment]
I've been looking into this because it ended up being necessary for addressing https://github.com/natcap/pygeoprocessing/issues/225 (and probably #672 by extension) and here are the high-level points I've found:

1. `setup.py` commands like `setup.py install` are being deprecated, but `setup.py` itself is not yet going away.
2. `python setup.py install` does not appear to work at all on Python 3.10
3. There exist ways and tooling to avoid using `setup.py` commands.

So there will come a time when we'll need to do away entirely with `setup.py`, but it doesn't look like we're there yet ... and there also doesn't seem like there's a well-documented way to build cython files without using `setuptools` anyways.  So I think for the time being, this should be a pretty straightfoward update to avoid the deprecation.

**Comment by phargogh** [comment]
Working on this in https://github.com/phargogh/invest/tree/task/717-setup.py-command-deprecation

**Comment by phargogh** [comment]
@emlys , regarding one of your comments in your post:
> I routinely use setup.py install, though our make install command already uses pip install which may be the correct alternative. Our setup.py also provides the build_ext command.

I don't yet know of a good way to build cython files without using setuptools.  But since the changes proposed in the blog post would be simply not using the `setup.py` command directly, I think we'll be ok for the time being until something better comes along.

It _seems_ like we have 2 solid replacements for `python setup.py install`:

1. `python -m build --wheel && python -m pip install natcap.invest --find-links=dist` (this is effectively what `make install` will do)
2. `python -m pip install -e .`, which will do an 'editable' install.  This was big news like 6 years ago, and while it does seem to ultimately call `python setup.py develop`, I'm not getting the `DeprecationWarning`s, so maybe it's OK?

I'm open to other alternatives as well if anyone has any!  This all seems like kind of frustrating, somewhat-uncharted territory where there isn't always a clear, recommended replacement.
