### ISSUE TITLE
Certificate Verify Fails on Mac

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#792]
@emlys noticed this on mac while we were preparing for the 3.10 release, noting:

> Not something that should hold up the release (probably not even related) but something is up with our usage logging:

```
2021-12-17 13:10:01,065 (natcap.invest.ui.usage._log_exit_status) usage._log_exit_status(195) WARNING an exception encountered when _log_exit_status <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
```

**Comment by emlys** [comment]
I just tried running carbon on main and release/3.10 and did not get this warning.

**Comment by dcdenu4** [comment]
Believe this to be related to usage logging.

**Comment by emlys** [comment]
Reproduced this with the 3.10.2 binaries (scenic quality). Could not reproduce with the 3.10.2 python package, with python 3.7, 8, or 9.

**Comment by emlys** [comment]
I suspect this is related: https://stackoverflow.com/a/42334357/14451410
Since the warning doesn't make it into the log file, this definitely could've been happening unnoticed since python 3.6. Perhaps the necessary post-install step isn't being run on the python version that we distribute in the binaries.
