### ISSUE TITLE
windows installation logs are meaningless

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#830]
`install_log.txt` and `install_data_log.txt` are both created in the installation folder on Windows. I don't recall what they used to contain, but I assume they are logs from NSIS script?

In my `3.10.1` installation, they both read like this - a random snippet from a 3000+ lines file:

```
C
C
C
C
O
E
E
O
E
E
E
```

**Comment by phargogh** [comment]
I'm certain this was originally intended to have been a log of everything that was installed ... there was a time when were were not so confident in our NSIS installer working as expected!  But that was probably back in like 2012 and I'm not sure if I've _ever_ looked at an installation log since then.  I'd personally be very OK if we removed these log files, particularly since they don't seem to be capturing anything useful.

**Comment by davemfish** [comment]
> I'm not sure if I've ever looked at an installation log since then. I'd personally be very OK if we removed these log files, particularly since they don't seem to be capturing anything useful.

Same. Just now I was actually looking for `package_versions.txt`, but couldn't remember its name or location so I mistakenly looked at these logs :)

**Comment by emlys** [comment]
Closing because we deprecated the QT interface!
