### ISSUE TITLE
Conda-forge package

### ISSUE THREAD

**Issue by TnTo** [natcap/invest#840]
Hi!

I have build a conda-forge package of invest.
A person in my uni need it for research and I tried (and hopefully succeeded) to create it.

The repository of the package is https://github.com/conda-forge/natcap.invest-feedstock and it should be sufficient to do `conda install natcap.invest -c conda-forge` to install invest even on linux.

I have no time to extensively test it and, in the long term, maintain it (especially the dependencies list).

If anyone can try to install invest in this way to test it, it will be great!
And if anyone wants to be added as maintainer of the conda-forge package it will be a pleasure.

**Comment by emlys** [comment]
Hi @TnTo,
Thanks for sharing this! It's awesome to see what folks are doing with invest.

I don't know if we'd be able to maintain a conda feedstock either - we haven't set one up before because of lack of demand and it's one more thing to maintain. @phargogh might know more about the history of that. But if there is growing demand we should consider it.

I tried it out and got an error `No such file or directory: '/Users/emily/opt/miniconda3/envs/t/lib/python3.9/site-packages/natcap/invest/unit_definitions.txt'`, but it looks like you've already fixed that, maybe it takes a bit to update the package index. The one-line install is a big improvement vs. having to `conda install gdal` then `pip install natcap.invest`. I'm curious if that convenience was the motivation for setting this up, or do you have a situation where `pip install` really doesn't work?

**Comment by TnTo** [comment]
Yes, I'm waiting for a repo update, build 1 should work

After `pip install` a strange `setattr` error appear on both arch linux and ubuntu. 
I was able to launch invest correctly once, but later the same commands doesn't work anymore...

Conda should be more reliable

**Comment by phargogh** [comment]
Well, I think there are a number of reasons why it hasn't made sense to do a `conda-forge` package historically, and @emlys is absolutely right that so far this is the one of the first times we've heard of a conda package being useful!  But it also wasn't practical to make a conda-forge until very recently, when the entire dependency tree was available as on conda-forge.

As for the maintenance burden, the `conda-forge` devs have done a good job of automating most things.  I've been casually maintaining conda-forge feedstocks for [`taskgraph`](https://github.com/conda-forge/taskgraph-feedstock) and [`pygeoprocessing`](https://github.com/conda-forge/pygeoprocessing-feedstock) for a while now and it's been pretty much fine.  There will of course be issues that come up in the future ... that's just how these things go.

@TnTo could you add me as a maintainer to this feedstock?  I'm happy to keep this up to date.

**Comment by TnTo** [comment]
The repos should be synced with the correct build (1) now!

**Comment by dcdenu4** [comment]
Hi @TnTo thanks for sharing this here. Could you add me as a maintainer as to this feedstock as well?
