### ISSUE TITLE
Check sampledata registry links is failing

### ISSUE THREAD

**Issue by emlys** [natcap/invest#902]
The sample data registry links have been returning 404 recently. This is causing our github actions workflow to fail.

**Comment by davemfish** [comment]
Oh interesting. There might be some real flaws in the system here. The registry `json` is updated during the build process, during the `make sampledata`. And then the test runs in that same job, so _should be_ referencing the updated `json` - the same one that is packaged into the workbench distribution. 

But then changes to `sampledata_registry.json` are never committed to the repo are they. So that might be a little annoying during development, if you wanted functional sampledata downloads. 

I'm not sure of the exact problems, but I'm happy to figure this out since I created them @emlys . Or it's yours if you want it!
