### ISSUE TITLE
UI-SERVER: shutdown method is deprecated

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#928]
Our approach to shutting down the dev server is now deprecated: `request.environ.get('werkzeug.server.shutdown')()`

Also I'm not sure why I ever set things up this way, to have the thread running the flask app try to shut its own server down. It's much easier to have the parent process be responsible for this.

Not shutting things down properly causes workbench tests to hang, and other problems.

**Comment by phargogh** [comment]
> Also I'm not sure why I ever set things up this way, to have the thread running the flask app try to shut its own server down. It's much easier to have the parent process be responsible for this.

I might have encouraged this.  The way concurrency is classically taught is that it's better to have a worker process shut itself down rather than be killed from the outside.  But for our purposes, it'd probably be better (not to mention more secure if we were running this in a web context) to allow the process to shut itself down when it receives `SIGINT`, which should only be able to come from the OS.
