### ISSUE TITLE
Annual Water Yield: combine watersheds and subwatersheds inputs?

### ISSUE THREAD

**Issue by emlys** [natcap/invest#969]
The watersheds and subwatersheds inputs are used in almost exactly the same way. The only difference is that valuation isn't done for subwatersheds. It's not clear to me why that distinction is made. Having just one watershed input would marginally simplify the code, sample data, and model interface and documentation.

**Comment by dcdenu4** [comment]
I can't recall the original decision to have a watershed and subwatershed option but my feeling is that working with these two scales is quite common in a project and that it's nice to have the outputs in the same workspace. If we had one input for ws/sws, then the naming would be the same for those output files, so it'd be harder to use the same workspace to aggregate results. Having said that, the suffix field is a way around that.

I wonder if @newtpatrol would have any insight into whether an analyses usually includes watersheds and subwatersheds, thus making both inputs present a nice convenience.

I'll also mention that there has been rumblings of maybe deprecating this model in favor of pointing people towards Seasonal Water Yield.

**Comment by emlys** [comment]
Thanks for the responses!
> it's nice to have the outputs in the same workspace

Agree, people shouldn't have to run the model twice to get watershed and sub-watershed results. Would it suffice to have the watershed and subwatersheds polygons all together in one vector? I'm pretty sure that the overlapping is not an issue

**Comment by newtpatrol** [comment]
It would be additional effort for people to combine the watershed with sub-watersheds into one vector (not much, but still some). And if they did package them that way for the model, they probably would not use it for any of their other work, since it's easier to layer and symbolize them separately for GIS and map-making purposes. 

And if people do what I usually do - provide the same watershed polygon as sub-watershed - then you'd have duplicate shapes in the vector file, which is confusing to work with.

**Comment by dcdenu4** [comment]
Just stumbled back upon this issue. Given this not being such a clear cut victory and things working well enough as it is, I'd vote to tag this as `wontfix` and close. What do you think @emlys ?

**Comment by emlys** [comment]
Sure!
